services:
  chappie_server:
    container_name: chappie_server
    restart: always
    ports:
      - "127.0.0.1:9111:9111"
    image: chappie_server:latest
    build:
      context: .
      dockerfile: Dockerfile
      args: APP_VERSION: ${APP_VERSION}
    env_file:
      - .env
    environment:
      TZ: Europe/Kiev
    networks:
      - chappie_network

networks:
  chappie_network:
    external: true