services:
  chappie:
    container_name: chappie
    restart: always
    ports:
      - "127.0.0.1:9001:9001"
    image: chappie:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      TZ: Europe/Kiev
    networks:
      - chappie_network

networks:
  chappie_network:
    external: true 